plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xeasy.noticefix'
    // 升级为高版本 Android 编译目标
    compileSdk 35

    defaultConfig {
        applicationId "com.xeasy.noticefix"
        minSdk 28
        targetSdk 35
        versionCode 38
        versionName "0.3.8_m3e"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // 升级为 Java 17 编译支持
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.9.0'

    // XML 解析
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.dom4j:dom4j:2.1.4'

    // 网络请求
    implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.14'

    // Root 权限操作库 (libsu)
    def libSuVersion = '5.2.1'
    implementation "com.github.topjohnwu.libsu:core:${libSuVersion}"
    implementation "com.github.topjohnwu.libsu:service:${libSuVersion}"
    implementation "com.github.topjohnwu.libsu:nio:${libSuVersion}"
    implementation "com.github.topjohnwu.libsu:io:${libSuVersion}"

    // JSON 解析
    implementation 'com.google.code.gson:gson:2.10.1'

    // 升级到 Material 3 现代界面核心库
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment:2.7.7'
    implementation 'androidx.navigation:navigation-ui:2.7.7'
    implementation 'androidx.preference:preference:1.2.1'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Xposed API
    compileOnly 'de.robv.android.xposed:api:82'
}
